### ISSUE TITLE
"NumberFormatException"

### ISSUE THREAD

**Issue by StarOfDoom** [mkremins/fanciful#74]
Hey!

Having some troubles with 1.10, it was working perfectly in 1.9

new FancyMessage("[Accept]")
	.color(ChatColor.GREEN)
	.command("/acceptduel")
	.tooltip("Accept The Duel!")
	.then(" ")
	.then("[Deny]")
	.color(ChatColor.RED)
	.command("/denyduel")
	.tooltip("Deny The Duel!")
	.send(player);

I get an error on .send(player) saying 

[13:20:20 WARN]: Argument could not be passed.
java.lang.NumberFormatException: For input string: "R"

Here is the full error

[13:20:20 WARN]: Argument could not be passed.
java.lang.NumberFormatException: For input string: "R"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_65]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_65]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_65]
	at mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:644) ~[Plugin.jar:?]
	at mkremins.fanciful.FancyMessage.send(FancyMessage.java:617) [Plugin.jar:?]
	at mkremins.fanciful.FancyMessage.send(FancyMessage.java:605) [Plugin.jar:?]
	at com.star.MAODueling.MAODueling.main.onClick(main.java:314) [Plugin.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1850) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-3ccadba-fb568fd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]

Any help? Thanks!

**Comment by mkremins** [comment]
Looks like a problem with the version parsing code, which had to be changed a few times in order to work with 1.10. The line numbers in the stack trace don't quite seem to match up with the latest version of Fanciful (`0.3.5-SNAPSHOT`) – are you using an older version of Fanciful, maybe?

**Comment by StarOfDoom** [comment]
Fixed. Hadn't updated correctly. I'm not smart haha. Sorry.

**Comment by runelynx** [comment]
I'm having the same issue... I've updated my Maven dependency to 0.3.5 and using the repository shown on this site. My Eclipse finds 0.3.5 and all its files just fine and builds out OK... but I still get the error on my server :(   What am I missing in the update process?

**Comment by Samuel98** [comment]
Works fine for me, after upgrading to latest version.

**Comment by runelynx** [comment]
But how are you upgrading to latest version? I've changed 0.3.3 to 0.3.5 in my POM, what else do I need to do?

**Comment by runelynx** [comment]
I've deleted 0.3.1 and 0.3.3 from my local mvn repository so it can only be using the 0.3.5 folder... I still get the error. What am I missing in the 'upgrade process' ??

**Comment by Stealth2800** [comment]
Are you using ```0.3.5-SNAPSHOT``` for the version?  Just ```0.3.5``` is incorrect.

**Comment by runelynx** [comment]
Yes, 0.3.5-SNAPSHOT. My Eclipse has all the files in the maven section so it finds it in your repository.

**Comment by Stealth2800** [comment]
Could you post the error stacktrace from your server please?

**Comment by runelynx** [comment]
Sigh. As life generally goes...  it now works fine. Thanks :-/
